// <auto-generated />
using System;
using APIconvenios.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIconvenios.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208224323_migracionFinal")]
    partial class migracionFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("APIconvenios.Models.ArchivosAdjuntos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConvenioEspecificoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConvenioMarcoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioEspecificoId");

                    b.HasIndex("ConvenioMarcoId");

                    b.ToTable("ArchivosAdjuntos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentType = "application/pdf",
                            ConvenioEspecificoId = 1,
                            NombreArchivo = "plan_trabajo.pdf",
                            RutaArchivo = "/uploads/especificos/plan_trabajo.pdf"
                        },
                        new
                        {
                            Id = 2,
                            ContentType = "application/pdf",
                            ConvenioEspecificoId = 1,
                            NombreArchivo = "acuerdo_confidencialidad.pdf",
                            RutaArchivo = "/uploads/especificos/acuerdo_confidencialidad.pdf"
                        },
                        new
                        {
                            Id = 3,
                            ContentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            ConvenioEspecificoId = 2,
                            NombreArchivo = "proyecto_investigacion_ia.docx",
                            RutaArchivo = "/uploads/especificos/proyecto_ia.docx"
                        },
                        new
                        {
                            Id = 4,
                            ContentType = "application/pdf",
                            ConvenioEspecificoId = 3,
                            NombreArchivo = "especificaciones_tecnicas.pdf",
                            RutaArchivo = "/uploads/especificos/especificaciones.pdf"
                        },
                        new
                        {
                            Id = 5,
                            ContentType = "application/pdf",
                            ConvenioEspecificoId = 4,
                            NombreArchivo = "programa_capacitacion.pdf",
                            RutaArchivo = "/uploads/especificos/programa_capacitacion.pdf"
                        },
                        new
                        {
                            Id = 6,
                            ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            ConvenioEspecificoId = 5,
                            NombreArchivo = "cronograma_actividades.xlsx",
                            RutaArchivo = "/uploads/especificos/cronograma.xlsx"
                        },
                        new
                        {
                            Id = 7,
                            ContentType = "application/pdf",
                            ConvenioEspecificoId = 6,
                            NombreArchivo = "informe_final_pfi.pdf",
                            RutaArchivo = "/uploads/especificos/informe_final.pdf"
                        },
                        new
                        {
                            Id = 8,
                            ContentType = "application/pdf",
                            ConvenioMarcoId = 1,
                            NombreArchivo = "convenio_marco_tech.pdf",
                            RutaArchivo = "/uploads/marcos/cm_tech.pdf"
                        },
                        new
                        {
                            Id = 9,
                            ContentType = "application/pdf",
                            ConvenioMarcoId = 1,
                            NombreArchivo = "resolucion_rectoral_001.pdf",
                            RutaArchivo = "/uploads/marcos/res_001.pdf"
                        },
                        new
                        {
                            Id = 10,
                            ContentType = "application/pdf",
                            ConvenioMarcoId = 2,
                            NombreArchivo = "convenio_marco_innovacion.pdf",
                            RutaArchivo = "/uploads/marcos/cm_innovacion.pdf"
                        },
                        new
                        {
                            Id = 11,
                            ContentType = "application/pdf",
                            ConvenioMarcoId = 3,
                            NombreArchivo = "convenio_marco_electronica.pdf",
                            RutaArchivo = "/uploads/marcos/cm_electronica.pdf"
                        },
                        new
                        {
                            Id = 12,
                            ContentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            ConvenioMarcoId = 4,
                            NombreArchivo = "borrador_convenio_quimica.docx",
                            RutaArchivo = "/uploads/marcos/borrador_quimica.docx"
                        });
                });

            modelBuilder.Entity("APIconvenios.Models.Carreras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carreras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Ingeniería Química"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Ingeniería en Sistemas"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Ingeniería Electrónica"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Ingeniería Electromecánica"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Tecnicatura en Programación"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Materias Basicas"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "SEU"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Vinculación Tecnológica"
                        });
                });

            modelBuilder.Entity("APIconvenios.Models.ConvenioEspecifico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComentarioOpcional")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConvenioMarcoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsActa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("FechaFinConvenio")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaFirmaConvenio")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaInicioActividades")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroResolucion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Refrendado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TituloConvenio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("numeroconvenio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioMarcoId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("ConveniosEspecificos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComentarioOpcional = "Pasantías rentadas para alumnos avanzados",
                            ConvenioMarcoId = 1,
                            EmpresaId = 1,
                            EsActa = false,
                            Estado = 1,
                            FechaFinConvenio = new DateOnly(2024, 12, 31),
                            FechaFirmaConvenio = new DateOnly(2024, 3, 1),
                            FechaInicioActividades = new DateOnly(2024, 3, 10),
                            NumeroResolucion = "RES-2024-015",
                            Refrendado = true,
                            TituloConvenio = "Pasantías 2024 - Sistemas y Programación",
                            numeroconvenio = "CE-001/2024"
                        },
                        new
                        {
                            Id = 2,
                            ComentarioOpcional = "Proyecto de investigación en IA",
                            ConvenioMarcoId = 2,
                            EmpresaId = 2,
                            EsActa = true,
                            Estado = 0,
                            FechaFinConvenio = new DateOnly(2024, 10, 30),
                            FechaFirmaConvenio = new DateOnly(2024, 4, 5),
                            FechaInicioActividades = new DateOnly(2024, 4, 10),
                            Refrendado = false,
                            TituloConvenio = "Investigación Conjunta AI",
                            numeroconvenio = "CE-002/2024"
                        },
                        new
                        {
                            Id = 3,
                            ConvenioMarcoId = 3,
                            EmpresaId = 3,
                            EsActa = false,
                            Estado = 1,
                            FechaFinConvenio = new DateOnly(2024, 11, 30),
                            FechaFirmaConvenio = new DateOnly(2024, 3, 20),
                            FechaInicioActividades = new DateOnly(2024, 4, 1),
                            NumeroResolucion = "RES-2024-022",
                            Refrendado = true,
                            TituloConvenio = "Desarrollo de Prototipos Electrónicos",
                            numeroconvenio = "CE-003/2024"
                        },
                        new
                        {
                            Id = 4,
                            EmpresaId = 6,
                            EsActa = false,
                            Estado = 1,
                            FechaFinConvenio = new DateOnly(2024, 7, 15),
                            FechaFirmaConvenio = new DateOnly(2024, 5, 15),
                            FechaInicioActividades = new DateOnly(2024, 5, 20),
                            NumeroResolucion = "RES-2024-035",
                            Refrendado = true,
                            TituloConvenio = "Capacitación SEU - Seguridad Laboral",
                            numeroconvenio = "CE-004/2024"
                        },
                        new
                        {
                            Id = 5,
                            EmpresaId = 4,
                            EsActa = false,
                            Estado = 1,
                            FechaFinConvenio = new DateOnly(2024, 8, 15),
                            FechaFirmaConvenio = new DateOnly(2024, 2, 10),
                            FechaInicioActividades = new DateOnly(2024, 2, 15),
                            NumeroResolucion = "RES-2024-008",
                            Refrendado = true,
                            TituloConvenio = "Prácticas Profesionales Química",
                            numeroconvenio = "CE-005/2024"
                        },
                        new
                        {
                            Id = 6,
                            ComentarioOpcional = "Proyecto finalizado con éxito",
                            ConvenioMarcoId = 3,
                            EmpresaId = 3,
                            EsActa = false,
                            Estado = 2,
                            FechaFinConvenio = new DateOnly(2023, 12, 20),
                            FechaFirmaConvenio = new DateOnly(2023, 8, 1),
                            FechaInicioActividades = new DateOnly(2023, 8, 10),
                            NumeroResolucion = "RES-2023-089",
                            Refrendado = true,
                            TituloConvenio = "Proyecto Final Integrador 2023",
                            numeroconvenio = "CE-006/2023"
                        },
                        new
                        {
                            Id = 7,
                            ConvenioMarcoId = 1,
                            EmpresaId = 1,
                            EsActa = true,
                            Estado = 1,
                            FechaFinConvenio = new DateOnly(2025, 7, 1),
                            FechaFirmaConvenio = new DateOnly(2024, 7, 1),
                            FechaInicioActividades = new DateOnly(2024, 7, 5),
                            NumeroResolucion = "RES-2024-055",
                            Refrendado = true,
                            TituloConvenio = "Acta Acuerdo Vinculación Tecnológica",
                            numeroconvenio = "ACTA-001/2024"
                        },
                        new
                        {
                            Id = 8,
                            ConvenioMarcoId = 5,
                            EmpresaId = 5,
                            EsActa = true,
                            Estado = 1,
                            FechaFinConvenio = new DateOnly(2024, 12, 31),
                            FechaFirmaConvenio = new DateOnly(2024, 6, 10),
                            FechaInicioActividades = new DateOnly(2024, 6, 15),
                            Refrendado = false,
                            TituloConvenio = "Acta Donación Equipamiento",
                            numeroconvenio = "ACTA-002/2024"
                        },
                        new
                        {
                            Id = 9,
                            ComentarioOpcional = "En negociación",
                            EmpresaId = 6,
                            EsActa = false,
                            Estado = 0,
                            Refrendado = false,
                            TituloConvenio = "Futuro Convenio Materias Básicas",
                            numeroconvenio = "CE-007/2024"
                        });
                });

            modelBuilder.Entity("APIconvenios.Models.ConvenioMarco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComentarioOpcional")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaFirmaConvenio")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroResolucion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Refrendado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("numeroconvenio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique();

                    b.ToTable("ConveniosMarcos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComentarioOpcional = "Convenio vigente principal para actividades IT",
                            EmpresaId = 1,
                            Estado = 1,
                            FechaFin = new DateOnly(2026, 1, 15),
                            FechaFirmaConvenio = new DateOnly(2024, 1, 15),
                            NumeroResolucion = "RES-2024-001",
                            Refrendado = true,
                            Titulo = "Convenio Marco con Tech Solutions",
                            numeroconvenio = "CM-001/2024"
                        },
                        new
                        {
                            Id = 2,
                            EmpresaId = 2,
                            Estado = 1,
                            FechaFin = new DateOnly(2025, 2, 20),
                            FechaFirmaConvenio = new DateOnly(2024, 2, 20),
                            Refrendado = false,
                            Titulo = "Convenio Marco con Innovación Digital",
                            numeroconvenio = "CM-002/2024"
                        },
                        new
                        {
                            Id = 3,
                            ComentarioOpcional = "Convenio finalizado exitosamente",
                            EmpresaId = 3,
                            Estado = 2,
                            FechaFin = new DateOnly(2024, 5, 10),
                            FechaFirmaConvenio = new DateOnly(2023, 5, 10),
                            NumeroResolucion = "RES-2023-045",
                            Refrendado = true,
                            Titulo = "Convenio Marco Electrónica - Finalizado",
                            numeroconvenio = "CM-003/2023"
                        },
                        new
                        {
                            Id = 4,
                            ComentarioOpcional = "En proceso de revisión legal",
                            EmpresaId = 4,
                            Estado = 0,
                            Refrendado = false,
                            Titulo = "Convenio Marco Química Industrial - Borrador",
                            numeroconvenio = "CM-004/2024"
                        },
                        new
                        {
                            Id = 5,
                            EmpresaId = 5,
                            Estado = 1,
                            FechaFin = new DateOnly(2027, 6, 1),
                            FechaFirmaConvenio = new DateOnly(2024, 6, 1),
                            NumeroResolucion = "RES-2024-078",
                            Refrendado = true,
                            Titulo = "Convenio Marco Mecatrónica",
                            numeroconvenio = "CM-005/2024"
                        });
                });

            modelBuilder.Entity("APIconvenios.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConvenioMarcoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cuit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cuit = "30-12345678-9",
                            Direccion = "Av. Tecnologica 123",
                            Email = "contacto@techsolutions.com",
                            Nombre = "Tech Solutions S.A.",
                            RazonSocial = "Tech Solutions S.A.",
                            Telefono = "3564112233"
                        },
                        new
                        {
                            Id = 2,
                            Cuit = "30-87654321-0",
                            Direccion = "Calle Innovacion 456",
                            Email = "info@innovacion.com",
                            Nombre = "Innovación Digital S.R.L.",
                            RazonSocial = "Innovación Digital S.R.L.",
                            Telefono = "3564445566"
                        },
                        new
                        {
                            Id = 3,
                            Cuit = "30-11223344-5",
                            Direccion = "Bv. Industrial 789",
                            Email = "contacto@electronica.com",
                            Nombre = "Electrónica Avanzada S.A.",
                            RazonSocial = "Electrónica Avanzada S.A.",
                            Telefono = "3564223344"
                        },
                        new
                        {
                            Id = 4,
                            Cuit = "30-99887766-1",
                            Direccion = "Parque Industrial 321",
                            Email = "info@quimica.com",
                            Nombre = "Química Industrial S.R.L.",
                            RazonSocial = "Química Industrial Soc. Resp. Limitada",
                            Telefono = "3564556677"
                        },
                        new
                        {
                            Id = 5,
                            Cuit = "30-55667788-2",
                            Direccion = "Av. Libertad 555",
                            Email = "ventas@mecatronica.com",
                            Nombre = "Mecatrónica del Centro",
                            RazonSocial = "Mecatrónica del Centro S.A.",
                            Telefono = "3564889900"
                        },
                        new
                        {
                            Id = 6,
                            Cuit = "30-44556677-3",
                            Direccion = "San Martin 888",
                            Email = "contacto@consultora.edu",
                            Nombre = "Consultora Educativa",
                            RazonSocial = "Consultora Educativa y Capacitación",
                            Telefono = "3564112244"
                        });
                });

            modelBuilder.Entity("APIconvenios.Models.Involucrados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CarrerasId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdCarrera")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Legajo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RolInvolucrado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarrerasId");

                    b.HasIndex("IdCarrera");

                    b.ToTable("Involucrados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Perez",
                            Email = "juan.perez@email.com",
                            IdCarrera = 2,
                            Legajo = 12345,
                            Nombre = "Juan",
                            RolInvolucrado = 1,
                            Telefono = "3564998877"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Martinez",
                            Email = "sofia.martinez@email.com",
                            IdCarrera = 5,
                            Legajo = 12346,
                            Nombre = "Sofia",
                            RolInvolucrado = 1,
                            Telefono = "3564887766"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Rodriguez",
                            Email = "lucas.rodriguez@email.com",
                            IdCarrera = 3,
                            Legajo = 12347,
                            Nombre = "Lucas",
                            RolInvolucrado = 1,
                            Telefono = "3564776655"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Gomez",
                            Email = "maria.gomez@email.com",
                            IdCarrera = 2,
                            Legajo = 67890,
                            Nombre = "Maria",
                            RolInvolucrado = 0,
                            Telefono = "3564776655"
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "Fernandez",
                            Email = "carlos.fernandez@utn.edu.ar",
                            IdCarrera = 6,
                            Legajo = 67891,
                            Nombre = "Carlos",
                            RolInvolucrado = 0,
                            Telefono = "3564665544"
                        },
                        new
                        {
                            Id = 6,
                            Apellido = "Lopez",
                            Email = "ana.lopez@utn.edu.ar",
                            IdCarrera = 1,
                            Legajo = 67892,
                            Nombre = "Ana",
                            RolInvolucrado = 0,
                            Telefono = "3564554433"
                        },
                        new
                        {
                            Id = 7,
                            Apellido = "Sanchez",
                            Email = "roberto.sanchez@utn.edu.ar",
                            IdCarrera = 7,
                            Legajo = 89001,
                            Nombre = "Roberto",
                            RolInvolucrado = 2,
                            Telefono = "3564443322"
                        },
                        new
                        {
                            Id = 8,
                            Apellido = "Diaz",
                            Email = "laura.diaz@utn.edu.ar",
                            IdCarrera = 7,
                            Legajo = 89002,
                            Nombre = "Laura",
                            RolInvolucrado = 2,
                            Telefono = "3564332211"
                        },
                        new
                        {
                            Id = 9,
                            Apellido = "Morales",
                            Email = "pedro.morales@techsolutions.com",
                            Nombre = "Pedro",
                            RolInvolucrado = 3,
                            Telefono = "3564221100"
                        },
                        new
                        {
                            Id = 10,
                            Apellido = "Torres",
                            Email = "gabriela.torres@innovacion.com",
                            Nombre = "Gabriela",
                            RolInvolucrado = 3,
                            Telefono = "3564110099"
                        },
                        new
                        {
                            Id = 11,
                            Apellido = "Ruiz",
                            Email = "miguel.ruiz@electronica.com",
                            Nombre = "Miguel",
                            RolInvolucrado = 3,
                            Telefono = "3564009988"
                        });
                });

            modelBuilder.Entity("CarrerasConvenioEspecifico", b =>
                {
                    b.Property<int>("CarreraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConvenioEspecificoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CarreraId", "ConvenioEspecificoId");

                    b.HasIndex("ConvenioEspecificoId");

                    b.ToTable("CarrerasConvenioEspecifico");

                    b.HasData(
                        new
                        {
                            CarreraId = 2,
                            ConvenioEspecificoId = 1
                        },
                        new
                        {
                            CarreraId = 5,
                            ConvenioEspecificoId = 1
                        },
                        new
                        {
                            CarreraId = 2,
                            ConvenioEspecificoId = 2
                        },
                        new
                        {
                            CarreraId = 3,
                            ConvenioEspecificoId = 3
                        },
                        new
                        {
                            CarreraId = 4,
                            ConvenioEspecificoId = 3
                        },
                        new
                        {
                            CarreraId = 1,
                            ConvenioEspecificoId = 4
                        },
                        new
                        {
                            CarreraId = 2,
                            ConvenioEspecificoId = 4
                        },
                        new
                        {
                            CarreraId = 3,
                            ConvenioEspecificoId = 4
                        },
                        new
                        {
                            CarreraId = 4,
                            ConvenioEspecificoId = 4
                        },
                        new
                        {
                            CarreraId = 7,
                            ConvenioEspecificoId = 4
                        },
                        new
                        {
                            CarreraId = 1,
                            ConvenioEspecificoId = 5
                        },
                        new
                        {
                            CarreraId = 6,
                            ConvenioEspecificoId = 5
                        },
                        new
                        {
                            CarreraId = 3,
                            ConvenioEspecificoId = 6
                        },
                        new
                        {
                            CarreraId = 2,
                            ConvenioEspecificoId = 7
                        },
                        new
                        {
                            CarreraId = 8,
                            ConvenioEspecificoId = 7
                        },
                        new
                        {
                            CarreraId = 1,
                            ConvenioEspecificoId = 8
                        },
                        new
                        {
                            CarreraId = 2,
                            ConvenioEspecificoId = 8
                        },
                        new
                        {
                            CarreraId = 3,
                            ConvenioEspecificoId = 8
                        },
                        new
                        {
                            CarreraId = 4,
                            ConvenioEspecificoId = 8
                        },
                        new
                        {
                            CarreraId = 6,
                            ConvenioEspecificoId = 9
                        });
                });

            modelBuilder.Entity("InvolucradosConvenioEspecifico", b =>
                {
                    b.Property<int>("ConvenioEspecificoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvolucradosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConvenioEspecificoId", "InvolucradosId");

                    b.HasIndex("InvolucradosId");

                    b.ToTable("InvolucradosConvenioEspecifico");

                    b.HasData(
                        new
                        {
                            ConvenioEspecificoId = 1,
                            InvolucradosId = 1
                        },
                        new
                        {
                            ConvenioEspecificoId = 1,
                            InvolucradosId = 2
                        },
                        new
                        {
                            ConvenioEspecificoId = 1,
                            InvolucradosId = 4
                        },
                        new
                        {
                            ConvenioEspecificoId = 1,
                            InvolucradosId = 9
                        },
                        new
                        {
                            ConvenioEspecificoId = 2,
                            InvolucradosId = 4
                        },
                        new
                        {
                            ConvenioEspecificoId = 2,
                            InvolucradosId = 5
                        },
                        new
                        {
                            ConvenioEspecificoId = 2,
                            InvolucradosId = 10
                        },
                        new
                        {
                            ConvenioEspecificoId = 3,
                            InvolucradosId = 3
                        },
                        new
                        {
                            ConvenioEspecificoId = 3,
                            InvolucradosId = 6
                        },
                        new
                        {
                            ConvenioEspecificoId = 3,
                            InvolucradosId = 11
                        },
                        new
                        {
                            ConvenioEspecificoId = 4,
                            InvolucradosId = 7
                        },
                        new
                        {
                            ConvenioEspecificoId = 4,
                            InvolucradosId = 8
                        },
                        new
                        {
                            ConvenioEspecificoId = 4,
                            InvolucradosId = 5
                        },
                        new
                        {
                            ConvenioEspecificoId = 5,
                            InvolucradosId = 1
                        },
                        new
                        {
                            ConvenioEspecificoId = 5,
                            InvolucradosId = 6
                        },
                        new
                        {
                            ConvenioEspecificoId = 6,
                            InvolucradosId = 3
                        },
                        new
                        {
                            ConvenioEspecificoId = 6,
                            InvolucradosId = 6
                        },
                        new
                        {
                            ConvenioEspecificoId = 7,
                            InvolucradosId = 7
                        },
                        new
                        {
                            ConvenioEspecificoId = 7,
                            InvolucradosId = 5
                        },
                        new
                        {
                            ConvenioEspecificoId = 7,
                            InvolucradosId = 9
                        },
                        new
                        {
                            ConvenioEspecificoId = 8,
                            InvolucradosId = 7
                        },
                        new
                        {
                            ConvenioEspecificoId = 8,
                            InvolucradosId = 8
                        },
                        new
                        {
                            ConvenioEspecificoId = 9,
                            InvolucradosId = 8
                        });
                });

            modelBuilder.Entity("APIconvenios.Models.ArchivosAdjuntos", b =>
                {
                    b.HasOne("APIconvenios.Models.ConvenioEspecifico", null)
                        .WithMany("ArchivosAdjuntos")
                        .HasForeignKey("ConvenioEspecificoId");

                    b.HasOne("APIconvenios.Models.ConvenioMarco", null)
                        .WithMany("ArchivosAdjuntos")
                        .HasForeignKey("ConvenioMarcoId");
                });

            modelBuilder.Entity("APIconvenios.Models.ConvenioEspecifico", b =>
                {
                    b.HasOne("APIconvenios.Models.ConvenioMarco", "ConvenioMarco")
                        .WithMany("ConveniosEspecificos")
                        .HasForeignKey("ConvenioMarcoId");

                    b.HasOne("APIconvenios.Models.Empresa", "empresa")
                        .WithMany("ConveniosEspecificos")
                        .HasForeignKey("EmpresaId");

                    b.Navigation("ConvenioMarco");

                    b.Navigation("empresa");
                });

            modelBuilder.Entity("APIconvenios.Models.ConvenioMarco", b =>
                {
                    b.HasOne("APIconvenios.Models.Empresa", "Empresa")
                        .WithOne("ConvenioMarco")
                        .HasForeignKey("APIconvenios.Models.ConvenioMarco", "EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("APIconvenios.Models.Involucrados", b =>
                {
                    b.HasOne("APIconvenios.Models.Carreras", null)
                        .WithMany("Involucrados")
                        .HasForeignKey("CarrerasId");

                    b.HasOne("APIconvenios.Models.Carreras", "Carrera")
                        .WithMany()
                        .HasForeignKey("IdCarrera");

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("CarrerasConvenioEspecifico", b =>
                {
                    b.HasOne("APIconvenios.Models.Carreras", null)
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIconvenios.Models.ConvenioEspecifico", null)
                        .WithMany()
                        .HasForeignKey("ConvenioEspecificoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvolucradosConvenioEspecifico", b =>
                {
                    b.HasOne("APIconvenios.Models.ConvenioEspecifico", null)
                        .WithMany()
                        .HasForeignKey("ConvenioEspecificoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIconvenios.Models.Involucrados", null)
                        .WithMany()
                        .HasForeignKey("InvolucradosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIconvenios.Models.Carreras", b =>
                {
                    b.Navigation("Involucrados");
                });

            modelBuilder.Entity("APIconvenios.Models.ConvenioEspecifico", b =>
                {
                    b.Navigation("ArchivosAdjuntos");
                });

            modelBuilder.Entity("APIconvenios.Models.ConvenioMarco", b =>
                {
                    b.Navigation("ArchivosAdjuntos");

                    b.Navigation("ConveniosEspecificos");
                });

            modelBuilder.Entity("APIconvenios.Models.Empresa", b =>
                {
                    b.Navigation("ConvenioMarco");

                    b.Navigation("ConveniosEspecificos");
                });
#pragma warning restore 612, 618
        }
    }
}
